import Head from "next/head";
import { NavBar, TweetsSection, BasicallyTheFooter } from "../../components/";

export const getStaticPaths = () => {
  return {
    paths: [
      {
        params: {
          user: "mohd",
        },
      },
    ],
    fallback: false,
  };
};

export const getStaticProps = (context) => {
  return {
    props: {
      user: context.params.user,
    },
  };
};

const User = ({ user }) => {
  console.log("asdasd");

  return (
    <div>
      <Head>
        <title>Twitter PERNG Clone | {user}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex justify-center flex-row bg-black text-twitter-text">
        <NavBar currentPage={"Home"} />
        <TweetsSection loading={true} />
        <BasicallyTheFooter />
      </main>
    </div>
  );
};

User.requireAuth = true;

export default User;
