export const AUTH_USER = "AUTH_USER"
export const AUTH_USER_LOADING = "AUTH_USER_LOADING"

export const AUTH_REGISTER = "AUTH_REGISTER"
export const AUTH_REGISTER_LOADING = "AUTH_REGISTER_LOADING"
export const AUTH_REGISTER_SUCCESS = "AUTH_REGISTER_SUCCESS"
export const AUTH_REGISTER_FAIL = "AUTH_REGISTER_FAIL"

export const AUTH_LOGIN = "AUTH_LOGIN"
export const AUTH_LOGIN_LOADING = "AUTH_LOGIN_LOADING"
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS"
export const AUTH_LOGIN_FAIL = "AUTH_LOGIN_FAIL"

export const AUTH_LOGOUT = "AUTH_LOGOUT"
export const AUTH_LOGOUT_LOADING = "AUTH_LOGOUT_LOADING"
export const AUTH_LOGOUT_SUCCESS = "AUTH_LOGOUT_SUCCESS"
export const AUTH_LOGOUT_FAIL = "AUTH_LOGOUT_FAIL"

export const ERRORS_FETCH = "ERRORS_FETCH"
export const ERRORS_CLEAR = "ERRORS_CLEAR"

export const SET_CHATS = "SET_CHATS"
export const CLEAR_CHATS = "CLEAR_CHATS"
export const SET_ACTIVE_CHAT = "SET_ACTIVE_CHAT"
export const CLEAR_ACTIVE_CHAT = "CLEAR_ACTIVE_CHAT"