import Head from "next/head";
import { useQuery } from "@apollo/react-hooks";
import { connect } from "react-redux"
import { FETCH_ALL_TWEETS } from "../apis/"
import { NavBar, TweetsSection, BasicallyTheFooter } from "../components/"
import { clearUser } from "../redux/actions/auth"
 
 const Home = (props) => {
  const { user, clearUser } = props;
  const { loading, data } = useQuery(FETCH_ALL_TWEETS);

  return (
    <div>
      <Head>
        <title>Twitter PERNG Clone | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex justify-center flex-row bg-black text-twitter-text">
        <NavBar logout={clearUser} currentUser={user} currentPage={"Home"} />
        { loading ? <h1>Loading...</h1> : <TweetsSection tweets={data.getTweets} />}
        <BasicallyTheFooter />
      </main>
    </div>
  );
}

const mapStateToProps = (state) => {
  return {
    user: state.auth.user,
  }
}

const mapDispatchToProps = (dispatch) => {
  return {
    clearUser: () => {
      dispatch(clearUser())
    }
  }
}

export default connect(mapStateToProps, mapDispatchToProps)(Home)