import Head from "next/head";
import { useQuery } from "@apollo/react-hooks";
import { FETCH_ALL_TWEETS } from "../apis/"
import { NavBar, TweetsSection, BasicallyTheFooter } from "../components/"

export default function Home() {
  const { loading, data } = useQuery(FETCH_ALL_TWEETS);

  return (
    <div>
      <Head>
        <title>Twitter PERNG Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex justify-center flex-row bg-black text-twitter-text">
        <NavBar />
        {
          loading ? <div>loading...</div> : <TweetsSection tweets={data.getTweets} />
        }
        <BasicallyTheFooter />
      </main>
    </div>
  );
}
