import Head from "next/head";
import Image from "next/image";
import { Avatar } from '@material-ui/core'
import MoreHorizIcon from '@mui/icons-material/MoreHoriz';
import { useQuery } from "@apollo/react-hooks";
import { FETCH_ALL_TWEETS } from "../apis/"
import { PageButton } from "../components/"

export default function Home() {
  const { loading, data } = useQuery(FETCH_ALL_TWEETS);

  return (
    <div>
      <Head>
        <title>Twitter PERNG Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex justify-center flex-row bg-black text-twitter-text">
        <div className="flex flex-col justify-between border-r-2 border-r-twitter-border w-[300px] min-h-screen">
          <div className="grid auto-rows-min justify-items-start">
            <div className="flex h-[50px] ml-5">
              <div className="self-center">
                <Image src="/images/logo.png" width="25" height="25" objectFit="contain" />
              </div>
            </div>

            <PageButton src="/images/logo.png" text="Home" />
            <PageButton src="/images/logo.png" text="Explore" />
            <PageButton src="/images/logo.png" text="Notifications" />
            <PageButton src="/images/logo.png" text="Messages" />
            <PageButton src="/images/logo.png" text="Bookmarks" />
            <PageButton src="/images/logo.png" text="Lists" />
            <PageButton src="/images/logo.png" text="Profile" />
            <PageButton src="/images/logo.png" text="More" />

            <div className="self-center bg-twitter-blue mt-5 w-4/5 rounded-full text-center py-3 hover:bg-twitter-blue-dark cursor-pointer">
              <h3 className="text-md font-bold">Tweet</h3>
            </div>
          </div>
          
          <div className="flex flex-row h-[50px] mb-5 justify-items-center justify-between">
            <div className="flex flex-col justify-center w-[50px]">
              <Avatar className="" />
            </div>
            <div className="flex flex-col grow mx-3 justify-around">
              <div className="">moh'd</div>
              <div className="">@zxcvbnmmohd</div>
            </div>
            <div className="flex flex-col justify-center w-[50px]">
              <MoreHorizIcon />
            </div>
          </div>
        </div>

        <div className="min-h-screen w-[600px]">
          <div className="flex flex-row h-[50px] place-content-between px-10">
            <h4 className="flex text-xl self-center">Home</h4>
            <Image classname="flex align-left" src="/images/logo.png" width="25" height="25" objectFit="contain" />
          </div>
        </div>

        <div className="border-l-2 border-l-twitter-border w-[400px] min-h-screen">
          Search
        </div>
      </main>
    </div>
  );
}
