import { useState } from "react";
import Router from "next/router";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useMutation } from "@apollo/react-hooks";
import Loader from "react-loader-spinner";
import { connect } from "react-redux"
import { REGISTER_USER } from "../apis/";
import { setUser } from "../redux/actions/auth"

const Register = (props) => {
  const { setUser } = props

  const [values, setValues] = useState({
    name: "",
    username: "",
    dob: Date.now(),
    email: "",
    password: "",
  });

  const [register, { loading }] = useMutation(REGISTER_USER, {
    update(_, result) {
      setUser(result.data.register);
      Router.push("/home");
    },
    onError: ({ graphQLErrors, networkError, operation, forward }) => {
      if (graphQLErrors) {
        console.log(graphQLErrors);
        for (let err of graphQLErrors) {
          console.log(err)
          switch (err.extensions.code) {
            case "UNAUTHENTICATED":
              const oldHeaders = operation.getContext().headers;
              operation.setContext({
                headers: {
                  ...oldHeaders,
                  authorization: getNewToken(),
                },
              });

              return forward(operation);
          }
        }
      }

      if (networkError) {
        console.log(`[Network error]: ${networkError}`);
      }
    },
    variables: values,
  });

  const onChange = (e) => {
    setValues({ ...values, [e.target.name]: e.target.value });
  };

  const onRegister = (e) => {
    e.preventDefault();
    register();
  };

  return (
    <div>
      <Head>
        <title>Twitter PERNG Clone | Register</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-row justify-center bg-twitter-blue text-twitter-text h-screen items-center">
        <div className="flex h-full w-full justify-center align-center">
          <Image
            src="/images/logo.png"
            width="250"
            height="250"
            objectFit="contain"
          />
        </div>

        <div className="flex h-full w-full justify-center bg-black">
          <div className="w-3/5 h-3/5 self-center bg-white text-black rounded-lg">
            <form
              className="flex flex-col justify-center items-center m-20"
              onSubmit={(e) => onRegister(e)}
            >
              <h1 className="text-2xl mb-5 text-center">Make a new account!</h1>

              <input
                className="w-4/5 h-[50px] mb-2 text-center rounded-full"
                placeholder="Name"
                name="name"
                type="text"
                value={values.name}
                onChange={(e) => onChange(e)}
              />
              <input
                className="w-4/5 h-[50px] mb-2 text-center rounded-full"
                placeholder="Username"
                name="username"
                type="text"
                value={values.username}
                onChange={(e) => onChange(e)}
              />
              <input
                className="w-4/5 h-[50px] mb-2 text-center rounded-full"
                placeholder="Date of Birth"
                name="dob"
                type="date"
                value={values.dob}
                onChange={(e) => onChange(e)}
              />
              <input
                className="w-4/5 h-[50px] mb-2 text-center rounded-full"
                placeholder="Email"
                name="email"
                type="email"
                value={values.email}
                onChange={(e) => onChange(e)}
              />
              <input
                className="w-4/5 h-[50px] mb-2 text-center rounded-full"
                placeholder="Password"
                name="password"
                type="password"
                value={values.password}
                onChange={(e) => onChange(e)}
              />

              <button
                className="w-4/5 h-[50px] mb-3 bg-twitter-blue rounded-full text-white"
                type="submit"
              >
                Register
              </button>

              <Link href="/" type="submit">
                <a>Or click here to Login</a>
              </Link>
            </form>
          </div>
        </div>
      </main>
    </div>
  );
}

const mapDispatchToProps = (dispatch) => {
  return {
    setUser: (user) => {
      dispatch(setUser(user))
    }
  }
}

export default connect(null, mapDispatchToProps)(Register)